# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - skip: true
  - id: dump
    dir: ./examples/dump
      # main: ./examples/dump
    binary: wtgDump
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    # List of combinations of GOOS + GOARCH + GOARM to ignore.
    # Default is empty.
    ignore:
      - goos: windows
        goarch: arm64
  - id: owm2dot
    dir: ./examples/owm2dot
      # main: ./examples/owm2dot
    binary: owm2dot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
  - id: owm2svg
    dir: ./examples/owm2svg
      #main: ./examples/owm2svg
    binary: owm2svg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
  - id: wtg2dot
    dir: ./examples/wtg2dot
      #main: ./examples/wtg2dot
    binary: wtg2dot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
  - id: wtg2svglive
    dir: ./examples/wtg2svglive
      #main: ./examples/wtg2svglive
    binary: wtg2svglive
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
  - id: wtg2svg
    dir: ./examples/wtg2svg
      #main: ./examples/wtg2svg
    binary: wtg2svg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
